[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:redis]
command=redis-server --protected-mode no
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:redpanda]
command=/usr/bin/rpk redpanda start --mode dev-container --kafka-addr 0.0.0.0:9092 --advertise-kafka-addr 127.0.0.1:9092
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:fastapi]
command=/workspace/.venv/bin/uvicorn backend.app.main:app --host 0.0.0.0 --port 7860
directory=/workspace
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=/workspace/.venv/bin/celery -A backend.app.services.celery_app.celery_app worker --loglevel=info 
environment=C_FORCE_ROOT="true"
directory=/workspace
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery-beat]
command=/workspace/.venv/bin/celery -A backend.app.services.celery_app.celery_app beat --loglevel=info --schedule=/tmp/celerybeat-schedule
environment=C_FORCE_ROOT="true"
directory=/workspace
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker]
command=/workspace/.venv/bin/python worker/worker.py
directory=/workspace
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0