"""add_alert_trigger_columns

Revision ID: 15639881888f
Revises: 1ffb20394fc4
Create Date: 2026-07-03 12:55:47.934133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15639881888f'
down_revision: Union[str, Sequence[str], None] = '1ffb20394fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_triggered', sa.Boolean(), nullable=False))
    op.add_column('alerts', sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'last_notified_at')
    op.drop_column('alerts', 'is_triggered')
    # ### end Alembic commands ###
