"""add saved strategies

Revision ID: 1ffb20394fc4
Revises: 3d7629451f7d
Create Date: 2026-06-30 18:25:18.681259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffb20394fc4'
down_revision: Union[str, Sequence[str], None] = '3d7629451f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('bullish_probability', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=5000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_strategies_ticker'), 'saved_strategies', ['ticker'], unique=False)
    op.create_index(op.f('ix_saved_strategies_user_id'), 'saved_strategies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_strategies_user_id'), table_name='saved_strategies')
    op.drop_index(op.f('ix_saved_strategies_ticker'), table_name='saved_strategies')
    op.drop_table('saved_strategies')
    # ### end Alembic commands ###
