"""add strategy_logs table

Revision ID: 887a33df9c3e
Revises: 31f4439fab74
Create Date: 2026-07-11 12:35:18.591942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887a33df9c3e'
down_revision: Union[str, Sequence[str], None] = '31f4439fab74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('bullish_probability', sa.Integer(), nullable=False),
    sa.Column('ai_entry', sa.Float(), nullable=False),
    sa.Column('ai_target', sa.Float(), nullable=False),
    sa.Column('ai_stop_loss', sa.Float(), nullable=False),
    sa.Column('user_entry', sa.Float(), nullable=False),
    sa.Column('user_target', sa.Float(), nullable=False),
    sa.Column('user_stop_loss', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_outcome', sa.String(length=20), nullable=True),
    sa.Column('user_outcome', sa.String(length=20), nullable=True),
    sa.Column('actual_exit_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_logs_status'), 'strategy_logs', ['status'], unique=False)
    op.create_index(op.f('ix_strategy_logs_ticker'), 'strategy_logs', ['ticker'], unique=False)
    op.create_index(op.f('ix_strategy_logs_timestamp'), 'strategy_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_strategy_logs_user_id'), 'strategy_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_logs_user_id'), table_name='strategy_logs')
    op.drop_index(op.f('ix_strategy_logs_timestamp'), table_name='strategy_logs')
    op.drop_index(op.f('ix_strategy_logs_ticker'), table_name='strategy_logs')
    op.drop_index(op.f('ix_strategy_logs_status'), table_name='strategy_logs')
    op.drop_table('strategy_logs')
    # ### end Alembic commands ###
