"""add_subscription_and_message_limit_columns

Revision ID: bbdbf37359be
Revises: 15639881888f
Create Date: 2026-07-04 19:07:25.250443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbdbf37359be'
down_revision: Union[str, Sequence[str], None] = '15639881888f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=50), server_default='free', nullable=False))
    op.add_column('users', sa.Column('messages_remaining', sa.Integer(), server_default='3', nullable=False))
    op.add_column('users', sa.Column('monthly_messages_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_billing_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_billing_date')
    op.drop_column('users', 'monthly_messages_used')
    op.drop_column('users', 'messages_remaining')
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###
