"""add_asset_class_columns

Revision ID: ea96300d7e57
Revises: 887a33df9c3e
Create Date: 2026-07-13 16:45:55.214049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea96300d7e57'
down_revision: Union[str, Sequence[str], None] = '887a33df9c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_logs', sa.Column('asset_class', sa.String(length=50), nullable=True))
    op.add_column('strategy_logs', sa.Column('asset_class', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_logs', 'asset_class')
    op.drop_column('prediction_logs', 'asset_class')
    # ### end Alembic commands ###
